repositories:
  - name: hashicorp
    url: https://helm.releases.hashicorp.com
  - name: external-secrets
    url: https://charts.external-secrets.io
  - name: helmforge
    url: https://repo.helmforge.dev
  - name: minio
    url: https://charts.min.io

releases:
  - name: vault
    namespace: vault
    createNamespace: true
    chart: hashicorp/vault
    version: 0.28.1
    values:
      - values/vault.yaml
    labels:
      stage: vault

  - name: external-secrets
    namespace: external-secrets
    createNamespace: true
    chart: external-secrets/external-secrets
    version: 0.10.0
    values:
      - values/external-secrets.yaml
    labels:
      stage: vault

  - name: eso-resources
    namespace: infra
    createNamespace: true
    chart: ./charts/eso-resources
    needs:
      - external-secrets/external-secrets
    labels:
      stage: secrets

  - name: postgresql
    namespace: infra
    createNamespace: true
    chart: helmforge/postgresql
    version: 2.0.4
    values:
      - values/postgresql.yaml
    strategicMergePatches:
      - patches/postgresql-volume-permissions.yaml
    needs:
      - infra/eso-resources
    labels:
      stage: infrastructure

  - name: rabbitmq
    namespace: infra
    createNamespace: true
    chart: helmforge/rabbitmq
    version: 1.6.1
    values:
      - values/rabbitmq.yaml
    needs:
      - infra/eso-resources
    labels:
      stage: infrastructure

  - name: minio
    namespace: infra
    chart: minio/minio
    version: 5.2.0
    values:
      - values/minio.yaml
    needs:
      - infra/eso-resources
    labels:
      stage: infrastructure

  - name: redis
    namespace: infra
    createNamespace: true
    chart: helmforge/redis
    version: 1.6.19
    values:
      - values/redis.yaml
    needs:
      - infra/eso-resources
    labels:
      stage: infrastructure
