Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.box_check_update = false
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = 3072
    vb.cpus = 2
  end

  config.vm.define "control_plane" do |control_plane|
    control_plane.vm.hostname = "control-plane"
    control_plane.vm.network "private_network", ip: "192.168.56.11"
  end

  config.vm.define "worker01" do |worker|
    worker.vm.hostname = "worker01"
    worker.vm.network "private_network", ip: "192.168.56.12"
  end

  # config.vm.define "worker02" do |worker|
  #   worker.vm.hostname = "worker02"
  #   worker.vm.network "private_network", ip: "192.168.56.13"
  # end
end