---
- name: get kubeadm join command
  ansible.builtin.shell: kubeadm token create --print-join-command
  register: join_token
  delegate_to: "{{ groups['control-plane'][0] }}"
  run_once: true

- name: ensure that node is already joined to cluster
  ansible.builtin.stat:
    path: /etc/kubernetes/kubelet.conf
  register: joined

- name: join k8s cluster
  ansible.builtin.shell: "{{ join_token.stdout }}"
  when: not joined.stat.exists
  